version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - /mongo-bd-web-2/

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: expressMongo
    environment: 
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_PORT: '27017'
    links: 
      - mongo
    ports:
      - "8081:8081"
